[package]
name = "hnd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
log = "0.4.22"
tokio = "1.41.1"
toml = "0.8.19"

[dev-dependencies]
assert_cmd = "2.0.16"
